Repository broadinstitute/gnomad_qc, pull requests merged in 2023-12, with the labels that each got.

#537 Move PCA files to under ancestry_inference
  gnomad_qc/v4/resources/sample_qc.py
Labels: Ancestry

#540 Add HGDP_TGP relatedness as a resource in v4
  gnomad_qc/v4/resources/sample_qc.py
Labels: Relatedness, HGDP/1KG

#536 Pass data_type to included datasets path function
  gnomad_qc/v4/create_release/create_release_sites_ht.py
  gnomad_qc/v4/resources/release.py
Labels: bug, v4, release
