Repository broadinstitute/gnomad_qc, pull requests merged in 2024-01, with the labels that each got.

#547 Change to use v3 test VDS instead of sparse MT
  gnomad_qc/v3/resources/basics.py
Labels: v3

#550 Add option to compute all sites allele number to v4 coverage script
  gnomad_qc/v4/annotations/compute_coverage.py
  gnomad_qc/v4/resources/constants.py
  gnomad_qc/v4/resources/release.py
Labels: Coverage, v4.1

#548 Update faf and popmax pops to remove to account for change in gnomad_methods
  gnomad_qc/v3/annotations/generate_freq_data.py
  gnomad_qc/v3/create_release/prepare_vcf_data_release.py
  gnomad_qc/v4/annotations/generate_freq.py
  gnomad_qc/v4/annotations/generate_freq_genomes.py
  gnomad_qc/v4/create_release/create_combined_faf_release_ht.py
  gnomad_qc/v4/create_release/validate_and_export_vcf.py
Labels: v3, v4, Frequency
