Repository broadinstitute/gnomad_qc, pull requests merged in 2024-02, with the labels that each got.

#553 Add sphinx documentation for v4 scripts and update doc strings accordingly
  .github/workflows/ci.yml
  .pre-commit-config.yaml
  README.md
  docs/.gitignore
  docs/README.md
  docs/_static/theme_overrides.css
  docs/build.sh
  docs/conf.py
  docs/directives.py
  docs/generate_api_reference.py
  docs/index.rst
  docs/requirements.docs.in
  docs/requirements.docs.txt
  gnomad_qc/v3/create_release/create_hgdp_tgp_subset.py
  gnomad_qc/v4/annotations/compute_coverage.py
  gnomad_qc/v4/annotations/generate_freq.py
  gnomad_qc/v4/annotations/generate_freq_genomes.py
  gnomad_qc/v4/annotations/generate_variant_qc_annotations.py
  gnomad_qc/v4/annotations/insilico_predictors.py
  gnomad_qc/v4/annotations/vep_context_ht.py
  gnomad_qc/v4/annotations/vrs_annotation_batch.py
  gnomad_qc/v4/create_release/create_combined_faf_release_ht.py
  gnomad_qc/v4/create_release/create_release_sites_ht.py
  gnomad_qc/v4/create_release/create_release_utils.py
  gnomad_qc/v4/create_release/make_var_annot_hists.py
  gnomad_qc/v4/create_release/validate_and_export_vcf.py
  gnomad_qc/v4/resources/annotations.py
  gnomad_qc/v4/resources/basics.py
  gnomad_qc/v4/resources/meta.py
  gnomad_qc/v4/resources/release.py
  gnomad_qc/v4/resources/sample_qc.py
  gnomad_qc/v4/resources/variant_qc.py
  gnomad_qc/v4/sample_qc/assign_ancestry.py
  gnomad_qc/v4/sample_qc/create_sample_qc_metadata_ht.py
  gnomad_qc/v4/sample_qc/create_sample_qc_metadata_ht_genomes.py
  gnomad_qc/v4/sample_qc/generate_qc_mt.py
  gnomad_qc/v4/sample_qc/hard_filters.py
  gnomad_qc/v4/sample_qc/identify_trios.py
  gnomad_qc/v4/sample_qc/interval_qc.py
  gnomad_qc/v4/sample_qc/outlier_filtering.py
  gnomad_qc/v4/sample_qc/platform_inference.py
  gnomad_qc/v4/sample_qc/relatedness.py
  gnomad_qc/v4/sample_qc/sex_inference.py
  gnomad_qc/v4/subset.py
  gnomad_qc/v4/variant_qc/evaluation.py
  gnomad_qc/v4/variant_qc/final_filter.py
  gnomad_qc/v4/variant_qc/final_filter_genomes.py
  gnomad_qc/v4/variant_qc/import_variant_qc_vcf.py
  gnomad_qc/v4/variant_qc/random_forest.py
  gnomad_qc/v4/variant_qc/vqsr.py
  lint
Labels: Documentation

#554 Add support for including mermaid flowcharts at the top of the sphinx documentation
  docs/conf.py
  docs/flowcharts/v4/index.mmd
  docs/generate_api_reference.py
  docs/requirements.docs.in
  docs/requirements.docs.txt
Labels: v4.1, Documentation

#546 Create script to create custom liftover file for 3 relevant genes
  gnomad_qc/v4/create_release/create_false_dup_liftover.py
  gnomad_qc/v4/resources/release.py
Labels: bug

#552 Adding my clean-up and changes for the AN and hist fixes
  gnomad_qc/v4/annotations/compute_coverage.py
  gnomad_qc/v4/annotations/fix_freq_an.py
  gnomad_qc/v4/resources/annotations.py
Labels: Frequency, v4.1

#557 Add steps to adjust the v4.0 freq with all sites an and hists and write out new v4.1 freq ht
  gnomad_qc/v4/annotations/fix_freq_an.py
Labels: Frequency, v4.1

#556 Add script to compute the 4.1 all sites an and qual hists for frequency updates
  gnomad_qc/v4/annotations/compute_coverage.py
  gnomad_qc/v4/annotations/fix_freq_an.py
  gnomad_qc/v4/resources/annotations.py
Labels: Frequency, Coverage, v4.1

#558 Align freq meta in v4.1 freq fix
  gnomad_qc/v4/annotations/fix_freq_an.py
Labels: Frequency, v4.1

#559 Small fixes made for runtime all sites AN and qual hists
  gnomad_qc/v4/annotations/fix_freq_an.py
Labels: Frequency, Coverage, v4.1

#560 Add all sites AN and qual stats computation for v4.1 genomes
  gnomad_qc/v3/resources/basics.py
  gnomad_qc/v4/annotations/compute_coverage.py
  gnomad_qc/v4/annotations/fix_freq_an.py
  gnomad_qc/v4/resources/annotations.py
  gnomad_qc/v4/resources/constants.py
Labels: Frequency, Coverage, v4.1
