Repository broadinstitute/gnomad_qc, pull requests merged in 2025-09, with the labels that each got.

#701 v4 subset fix sparse split multi filter changed loci
  gnomad_qc/v4/subset.py
Labels: v4

#706 Small fixes to sample QC outlier
  gnomad_qc/v5/sample_qc/outlier_filtering.py
Labels: v5

#709 Add markdown to direct dependency list
  requirements.txt
Labels: dependencies

#719 Show the GCS migration warning only once
  gnomad_qc/v3/resources/annotations.py
  gnomad_qc/v3/resources/resource_utils.py
  gnomad_qc/v3/resources/sample_qc.py
  gnomad_qc/v5/data_ingestion/field_md_to_html.py
Labels: bug, v3
